package mg.aldamah.beans;
// Generated 29 sept. 2018 16:11:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Site generated by hbm2java
 */
public class Site  implements java.io.Serializable {


     private Integer siteId;
     private String siteNom;
     private String siteLieu;
     private int siteTarifjournaliere;
     private Set visiters = new HashSet(0);

    public Site() {
    }

	
    public Site(String siteNom, String siteLieu, int siteTarifjournaliere) {
        this.siteNom = siteNom;
        this.siteLieu = siteLieu;
        this.siteTarifjournaliere = siteTarifjournaliere;
    }
    public Site(String siteNom, String siteLieu, int siteTarifjournaliere, Set visiters) {
       this.siteNom = siteNom;
       this.siteLieu = siteLieu;
       this.siteTarifjournaliere = siteTarifjournaliere;
       this.visiters = visiters;
    }
   
    public Integer getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
    public String getSiteNom() {
        return this.siteNom;
    }
    
    public void setSiteNom(String siteNom) {
        this.siteNom = siteNom;
    }
    public String getSiteLieu() {
        return this.siteLieu;
    }
    
    public void setSiteLieu(String siteLieu) {
        this.siteLieu = siteLieu;
    }
    public int getSiteTarifjournaliere() {
        return this.siteTarifjournaliere;
    }
    
    public void setSiteTarifjournaliere(int siteTarifjournaliere) {
        this.siteTarifjournaliere = siteTarifjournaliere;
    }
    public Set getVisiters() {
        return this.visiters;
    }
    
    public void setVisiters(Set visiters) {
        this.visiters = visiters;
    }




}


